name: K_Skill
description: "An English Learning Platform"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  my_app: ^1.0.0
  audioplayers: ^6.5.0
  speech_to_text: ^7.1.0
  http: ^1.4.0
  flutter_tts: ^4.2.3
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.7+1
  string_similarity: ^2.0.0
  permission_handler: ^12.0.1
  flutter_sound: ^9.28.0
  record: ^6.0.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "images/kskill_logo.png"

flutter:
  uses-material-design: true

  assets:

  #assessment
  - assets/data/assessment/listening_sentence.json
  - assets/data/assessment/quiz_questions.json
  - assets/data/assessment/reading_passage.json

  #practice
  - assets/data/practice/listening_sentences.json
  - assets/data/practice/reading_passages.json
  - assets/data/practice/discourse.json
  
  #logos
  - assets/images/boy.png
  - assets/images/girl.png
  - assets/images/kskill_logo.png
  - assets/images/children.jpg
  - assets/images/login_side_image.png

  - assets/images/board.png

  - assets/images/games/

  - assets/games/grammar_mistakes.json
  - assets/games/listening_puzzle.json
  - assets/games/picture_sentence.json
  - assets/games/sentence_formation.json
  - assets/games/story_completion.json
  - assets/games/word_match.json

  #academics
  - assets/data/lessons/academic_curriculum.json

  - assets/data/lessons/class8/
  - assets/data/lessons/class9/
  - assets/data/lessons/class10/
  
  - assets/data/lessons/class8/unit1/C8_U1_A.json
  - assets/data/lessons/class8/unit1/C8_U1_B.json
  - assets/data/lessons/class8/unit1/C8_U1_C.json

  - assets/data/lessons/class8/unit2/C8_U2_A.json
  - assets/data/lessons/class8/unit2/C8_U2_B.json
  - assets/data/lessons/class8/unit2/C8_U2_C.json

  - assets/data/lessons/class8/unit3/C8_U3_A.json
  - assets/data/lessons/class8/unit3/C8_U3_B.json
  - assets/data/lessons/class8/unit3/C8_U3_C.json

  - assets/data/lessons/class8/unit4/C8_U4_A.json
  - assets/data/lessons/class8/unit4/C8_U4_B.json
  - assets/data/lessons/class8/unit4/C8_U4_C.json

  - assets/data/lessons/class8/unit5/C8_U5_A.json
  - assets/data/lessons/class8/unit5/C8_U5_B.json
  - assets/data/lessons/class8/unit5/C8_U5_C.json

  - assets/data/lessons/class8/unit6/C8_U6_A.json
  - assets/data/lessons/class8/unit6/C8_U6_B.json
  - assets/data/lessons/class8/unit6/C8_U6_C.json

  - assets/data/lessons/class8/unit7/C8_U7_A.json
  - assets/data/lessons/class8/unit7/C8_U7_B.json
  - assets/data/lessons/class8/unit7/C8_U7_C.json

  - assets/data/lessons/class8/unit8/C8_U8_A.json
  - assets/data/lessons/class8/unit8/C8_U8_B.json
  - assets/data/lessons/class8/unit8/C8_U8_C.json

  - assets/data/lessons/class9/unit1/
  - assets/data/lessons/class9/unit2/
  - assets/data/lessons/class9/unit3/
  - assets/data/lessons/class9/unit4/
  - assets/data/lessons/class9/unit5/
  - assets/data/lessons/class9/unit6/
  - assets/data/lessons/class9/unit7/
  - assets/data/lessons/class9/unit8/

  - assets/data/lessons/class10/unit1/
  - assets/data/lessons/class10/unit2/
  - assets/data/lessons/class10/unit3/
  - assets/data/lessons/class10/unit4/
  - assets/data/lessons/class10/unit5/
  - assets/data/lessons/class10/unit6/
  - assets/data/lessons/class10/unit7/
  - assets/data/lessons/class10/unit8/

    
  - assets/data/lessons/class9/unit1/C9_U1_A.json
  - assets/data/lessons/class9/unit1/C9_U1_B.json
  - assets/data/lessons/class9/unit1/C9_U1_C.json

  - assets/data/lessons/class9/unit2/C9_U2_A.json
  - assets/data/lessons/class9/unit2/C9_U2_B.json
  - assets/data/lessons/class9/unit2/C9_U2_C.json

  - assets/data/lessons/class9/unit3/C9_U3_A.json
  - assets/data/lessons/class9/unit3/C9_U3_B.json
  - assets/data/lessons/class9/unit3/C9_U3_C.json

  - assets/data/lessons/class9/unit4/C9_U4_A.json
  - assets/data/lessons/class9/unit4/C9_U4_B.json
  - assets/data/lessons/class9/unit4/C9_U4_C.json

  - assets/data/lessons/class9/unit5/C9_U5_A.json
  - assets/data/lessons/class9/unit5/C9_U5_B.json
  - assets/data/lessons/class9/unit5/C9_U5_C.json

  - assets/data/lessons/class9/unit6/C9_U6_A.json
  - assets/data/lessons/class9/unit6/C9_U6_B.json
  - assets/data/lessons/class9/unit6/C9_U6_C.json

  - assets/data/lessons/class9/unit7/C9_U7_A.json
  - assets/data/lessons/class9/unit7/C9_U7_B.json
  - assets/data/lessons/class9/unit7/C9_U7_C.json

  - assets/data/lessons/class9/unit8/C9_U8_A.json
  - assets/data/lessons/class9/unit8/C9_U8_B.json
  - assets/data/lessons/class9/unit8/C9_U8_C.json

    
  - assets/data/lessons/class10/unit1/C10_U1_A.json
  - assets/data/lessons/class10/unit1/C10_U1_B.json
  - assets/data/lessons/class10/unit1/C10_U1_C.json

  - assets/data/lessons/class10/unit2/C10_U2_A.json
  - assets/data/lessons/class10/unit2/C10_U2_B.json
  - assets/data/lessons/class10/unit2/C10_U2_C.json

  - assets/data/lessons/class10/unit3/C10_U3_A.json
  - assets/data/lessons/class10/unit3/C10_U3_B.json
  - assets/data/lessons/class10/unit3/C10_U3_C.json

  - assets/data/lessons/class10/unit4/C10_U4_A.json
  - assets/data/lessons/class10/unit4/C10_U4_B.json
  - assets/data/lessons/class10/unit4/C10_U4_C.json

  - assets/data/lessons/class10/unit5/C10_U5_A.json
  - assets/data/lessons/class10/unit5/C10_U5_B.json
  - assets/data/lessons/class10/unit5/C10_U5_C.json

  - assets/data/lessons/class10/unit6/C10_U6_A.json
  - assets/data/lessons/class10/unit6/C10_U6_B.json
  - assets/data/lessons/class10/unit6/C10_U6_C.json

  - assets/data/lessons/class10/unit7/C10_U7_A.json
  - assets/data/lessons/class10/unit7/C10_U7_B.json
  - assets/data/lessons/class10/unit7/C10_U7_C.json

  - assets/data/lessons/class10/unit8/C10_U8_A.json
  - assets/data/lessons/class10/unit8/C10_U8_B.json
  - assets/data/lessons/class10/unit8/C10_U8_C.json

  #lessons
  - assets/data/lessons/english_curriculum.json

  - assets/data/lessons/basic/
  - assets/data/lessons/intermediate/
  - assets/data/lessons/advanced/

  - assets/data/lessons/basic/module-1/L1_M1_L1.json
  - assets/data/lessons/basic/module-1/L1_M1_L2.json
  - assets/data/lessons/basic/module-1/L1_M1_L3.json

  - assets/data/lessons/basic/module-2/L1_M2_L1.json
  - assets/data/lessons/basic/module-2/L1_M2_L2.json
  - assets/data/lessons/basic/module-2/L1_M2_L3.json
  - assets/data/lessons/basic/module-2/L1_M2_L4.json
  - assets/data/lessons/basic/module-2/L1_M2_L5.json

  
  - assets/data/lessons/basic/module-3/L1_M3_L1.json
  - assets/data/lessons/basic/module-3/L1_M3_L2.json 
  - assets/data/lessons/basic/module-3/L1_M3_L3.json 
  - assets/data/lessons/basic/module-3/L1_M3_L4.json 
  - assets/data/lessons/basic/module-3/L1_M3_L5.json 
  - assets/data/lessons/basic/module-3/L1_M3_L6.json 

  - assets/data/lessons/basic/module-4/L1_M4_L1.json
  - assets/data/lessons/basic/module-4/L1_M4_L2.json 
  - assets/data/lessons/basic/module-4/L1_M4_L3.json 
  - assets/data/lessons/basic/module-4/L1_M4_L4.json 
  - assets/data/lessons/basic/module-4/L1_M4_L5.json 
  - assets/data/lessons/basic/module-4/L1_M4_L6.json 
  - assets/data/lessons/basic/module-4/L1_M4_L7.json 
  - assets/data/lessons/basic/module-4/L1_M4_L8.json

  - assets/data/lessons/basic/module-5/L1_M5_L1.json
  - assets/data/lessons/basic/module-5/L1_M5_L2.json
  - assets/data/lessons/basic/module-5/L1_M5_L3.json

  - assets/data/lessons/basic/module-6/L1_M6_L1.json
  - assets/data/lessons/basic/module-6/L1_M6_L2.json
  - assets/data/lessons/basic/module-6/L1_M6_L3.json
  - assets/data/lessons/basic/module-6/L1_M6_L4.json
  - assets/data/lessons/basic/module-6/L1_M6_L5.json

  - assets/data/lessons/intermediate/module-1/L2_M1_L1.json
  - assets/data/lessons/intermediate/module-1/L2_M1_L2.json
  - assets/data/lessons/intermediate/module-1/L2_M1_L3.json
  - assets/data/lessons/intermediate/module-1/L2_M1_L4.json
  - assets/data/lessons/intermediate/module-1/L2_M1_L5.json

  - assets/data/lessons/intermediate/module-2/L2_M2_L1.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L2.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L3.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L4.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L5.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L6.json
  - assets/data/lessons/intermediate/module-2/L2_M2_L7.json

  - assets/data/lessons/intermediate/module-3/L2_M3_L1.json
  - assets/data/lessons/intermediate/module-3/L2_M3_L2.json
  - assets/data/lessons/intermediate/module-3/L2_M3_L3.json
  - assets/data/lessons/intermediate/module-3/L2_M3_L4.json
  - assets/data/lessons/intermediate/module-3/L2_M3_L5.json

  - assets/data/lessons/intermediate/module-4/L2_M4_L1.json
  - assets/data/lessons/intermediate/module-4/L2_M4_L2.json
  - assets/data/lessons/intermediate/module-4/L2_M4_L3.json
  - assets/data/lessons/intermediate/module-4/L2_M4_L4.json
  - assets/data/lessons/intermediate/module-4/L2_M4_L5.json

  - assets/data/lessons/intermediate/module-5/L2_M5_L1.json
  - assets/data/lessons/intermediate/module-5/L2_M5_L2.json
  - assets/data/lessons/intermediate/module-5/L2_M5_L3.json
  - assets/data/lessons/intermediate/module-5/L2_M5_L4.json
  - assets/data/lessons/intermediate/module-5/L2_M5_L5.json

  - assets/data/lessons/advanced/module-1/L3_M1_L1.json
  - assets/data/lessons/advanced/module-1/L3_M1_L2.json
  - assets/data/lessons/advanced/module-1/L3_M1_L3.json
  - assets/data/lessons/advanced/module-1/L3_M1_L4.json

  - assets/data/lessons/advanced/module-2/L3_M2_L1.json
  - assets/data/lessons/advanced/module-2/L3_M2_L2.json
  - assets/data/lessons/advanced/module-2/L3_M2_L3.json
  - assets/data/lessons/advanced/module-2/L3_M2_L4.json

  - assets/data/lessons/advanced/module-3/L3_M3_L1.json
  - assets/data/lessons/advanced/module-3/L3_M3_L2.json
  - assets/data/lessons/advanced/module-3/L3_M3_L3.json
  - assets/data/lessons/advanced/module-3/L3_M3_L4.json

  - assets/data/lessons/advanced/module-4/L3_M4_L1.json
  - assets/data/lessons/advanced/module-4/L3_M4_L2.json
  - assets/data/lessons/advanced/module-4/L3_M4_L3.json
  - assets/data/lessons/advanced/module-4/L3_M4_L4.json

  #quizzes
  - assets/data/quizzes/
  - assets/data/quizzes/basic/
  - assets/data/quizzes/intermediate/
  - assets/data/quizzes/advanced/

  - assets/data/quizzes/basic/module-1/L1_M1_Q1.json
  - assets/data/quizzes/basic/module-1/L1_M1_Q2.json
  - assets/data/quizzes/basic/module-1/L1_M1_Q3.json

  - assets/data/quizzes/basic/module-2/L1_M2_Q1.json
  - assets/data/quizzes/basic/module-2/L1_M2_Q2.json
  - assets/data/quizzes/basic/module-2/L1_M2_Q3.json
  - assets/data/quizzes/basic/module-2/L1_M2_Q4.json
  - assets/data/quizzes/basic/module-2/L1_M2_Q5.json

  
  - assets/data/quizzes/basic/module-3/L1_M3_Q1.json
  - assets/data/quizzes/basic/module-3/L1_M3_Q2.json 
  - assets/data/quizzes/basic/module-3/L1_M3_Q3.json 
  - assets/data/quizzes/basic/module-3/L1_M3_Q4.json 
  - assets/data/quizzes/basic/module-3/L1_M3_Q5.json 
  - assets/data/quizzes/basic/module-3/L1_M3_Q6.json 

  - assets/data/quizzes/basic/module-4/L1_M4_Q1.json
  - assets/data/quizzes/basic/module-4/L1_M4_Q2.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q3.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q4.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q5.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q6.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q7.json 
  - assets/data/quizzes/basic/module-4/L1_M4_Q8.json

  - assets/data/quizzes/basic/module-5/L1_M5_Q1.json
  - assets/data/quizzes/basic/module-5/L1_M5_Q2.json
  - assets/data/quizzes/basic/module-5/L1_M5_Q3.json

  - assets/data/quizzes/basic/module-6/L1_M6_Q1.json
  - assets/data/quizzes/basic/module-6/L1_M6_Q2.json
  - assets/data/quizzes/basic/module-6/L1_M6_Q3.json
  - assets/data/quizzes/basic/module-6/L1_M6_Q4.json
  - assets/data/quizzes/basic/module-6/L1_M6_Q5.json

  - assets/data/quizzes/intermediate/module-1/L2_M1_Q1.json
  - assets/data/quizzes/intermediate/module-1/L2_M1_Q2.json
  - assets/data/quizzes/intermediate/module-1/L2_M1_Q3.json
  - assets/data/quizzes/intermediate/module-1/L2_M1_Q4.json
  - assets/data/quizzes/intermediate/module-1/L2_M1_Q5.json

  - assets/data/quizzes/intermediate/module-2/L2_M2_Q1.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q2.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q3.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q4.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q5.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q6.json
  - assets/data/quizzes/intermediate/module-2/L2_M2_Q7.json

  - assets/data/quizzes/intermediate/module-3/L2_M3_Q1.json
  - assets/data/quizzes/intermediate/module-3/L2_M3_Q2.json
  - assets/data/quizzes/intermediate/module-3/L2_M3_Q3.json
  - assets/data/quizzes/intermediate/module-3/L2_M3_Q4.json
  - assets/data/quizzes/intermediate/module-3/L2_M3_Q5.json

  - assets/data/quizzes/intermediate/module-4/L2_M4_Q1.json
  - assets/data/quizzes/intermediate/module-4/L2_M4_Q2.json
  - assets/data/quizzes/intermediate/module-4/L2_M4_Q3.json
  - assets/data/quizzes/intermediate/module-4/L2_M4_Q4.json
  - assets/data/quizzes/intermediate/module-4/L2_M4_Q5.json

  - assets/data/quizzes/intermediate/module-5/L2_M5_Q1.json
  - assets/data/quizzes/intermediate/module-5/L2_M5_Q2.json
  - assets/data/quizzes/intermediate/module-5/L2_M5_Q3.json
  - assets/data/quizzes/intermediate/module-5/L2_M5_Q4.json
  - assets/data/quizzes/intermediate/module-5/L2_M5_Q5.json

  - assets/data/quizzes/advanced/module-1/L3_M1_Q1.json
  - assets/data/quizzes/advanced/module-1/L3_M1_Q2.json
  - assets/data/quizzes/advanced/module-1/L3_M1_Q3.json
  - assets/data/quizzes/advanced/module-1/L3_M1_Q4.json

  - assets/data/quizzes/advanced/module-2/L3_M2_Q1.json
  - assets/data/quizzes/advanced/module-2/L3_M2_Q2.json
  - assets/data/quizzes/advanced/module-2/L3_M2_Q3.json
  - assets/data/quizzes/advanced/module-2/L3_M2_Q4.json

  - assets/data/quizzes/advanced/module-3/L3_M3_Q1.json
  - assets/data/quizzes/advanced/module-3/L3_M3_Q2.json
  - assets/data/quizzes/advanced/module-3/L3_M3_Q3.json
  - assets/data/quizzes/advanced/module-3/L3_M3_Q4.json

  - assets/data/quizzes/advanced/module-4/L3_M4_Q1.json
  - assets/data/quizzes/advanced/module-4/L3_M4_Q2.json
  - assets/data/quizzes/advanced/module-4/L3_M4_Q3.json
  - assets/data/quizzes/advanced/module-4/L3_M4_Q4.json

  - assets/images/

  #images for each lesson
  - assets/images/
  - assets/images/basic/
  - assets/images/intermediate/
  - assets/images/advanced/

  - assets/images/basic/module-1/lesson-1/
  - assets/images/basic/module-1/lesson-2/
  - assets/images/basic/module-1/lesson-3/

  - assets/images/basic/module-2/lesson-1/
  - assets/images/basic/module-2/lesson-2/
  - assets/images/basic/module-2/lesson-3/
  - assets/images/basic/module-2/lesson-4/
  - assets/images/basic/module-2/lesson-5/  

  - assets/images/basic/module-3/lesson-1/
  - assets/images/basic/module-3/lesson-2/
  - assets/images/basic/module-3/lesson-3/
  - assets/images/basic/module-3/lesson-4/
  - assets/images/basic/module-3/lesson-5/
  - assets/images/basic/module-3/lesson-6/

  - assets/images/basic/module-4/lesson-1/
  - assets/images/basic/module-4/lesson-2/
  - assets/images/basic/module-4/lesson-3/
  - assets/images/basic/module-4/lesson-4/
  - assets/images/basic/module-4/lesson-5/
  - assets/images/basic/module-4/lesson-6/
  - assets/images/basic/module-4/lesson-7/
  - assets/images/basic/module-4/lesson-8/

  - assets/images/basic/module-5/lesson-1/
  - assets/images/basic/module-5/lesson-2/
  - assets/images/basic/module-5/lesson-3/

  - assets/images/basic/module-6/lesson-1/
  - assets/images/basic/module-6/lesson-2/
  - assets/images/basic/module-6/lesson-3/
  - assets/images/basic/module-6/lesson-4/
  - assets/images/basic/module-6/lesson-5/

  - assets/images/intermediate/module-1/lesson-1/
  - assets/images/intermediate/module-1/lesson-2/
  - assets/images/intermediate/module-1/lesson-3/
  - assets/images/intermediate/module-1/lesson-4/
  - assets/images/intermediate/module-1/lesson-5/

  - assets/images/intermediate/module-2/lesson-1/
  - assets/images/intermediate/module-2/lesson-2/
  - assets/images/intermediate/module-2/lesson-3/
  - assets/images/intermediate/module-2/lesson-4/
  - assets/images/intermediate/module-2/lesson-5/
  - assets/images/intermediate/module-2/lesson-6/
  - assets/images/intermediate/module-2/lesson-7/

  - assets/images/intermediate/module-3/lesson-1/
  - assets/images/intermediate/module-3/lesson-2/
  - assets/images/intermediate/module-3/lesson-3/
  - assets/images/intermediate/module-3/lesson-4/
  - assets/images/intermediate/module-3/lesson-5/

  - assets/images/intermediate/module-4/lesson-1/
  - assets/images/intermediate/module-4/lesson-2/
  - assets/images/intermediate/module-4/lesson-3/
  - assets/images/intermediate/module-4/lesson-4/
  - assets/images/intermediate/module-4/lesson-5/

  - assets/images/intermediate/module-5/lesson-1/
  - assets/images/intermediate/module-5/lesson-2/
  - assets/images/intermediate/module-5/lesson-3/
  - assets/images/intermediate/module-5/lesson-4/
  - assets/images/intermediate/module-5/lesson-5/

  - assets/images/advanced/module-1/lesson-1/
  - assets/images/advanced/module-1/lesson-2/
  - assets/images/advanced/module-1/lesson-3/
  - assets/images/advanced/module-1/lesson-4/

  - assets/images/advanced/module-2/lesson-1/
  - assets/images/advanced/module-2/lesson-2/
  - assets/images/advanced/module-2/lesson-3/
  - assets/images/advanced/module-2/lesson-4/

  - assets/images/advanced/module-3/lesson-1/
  - assets/images/advanced/module-3/lesson-2/
  - assets/images/advanced/module-3/lesson-3/
  - assets/images/advanced/module-3/lesson-4/

  - assets/images/advanced/module-4/lesson-1/
  - assets/images/advanced/module-4/lesson-2/
  - assets/images/advanced/module-4/lesson-3/
  - assets/images/advanced/module-4/lesson-4/

  - assets/images/class8/unit1/
  - assets/images/class8/unit2/
  - assets/images/class8/unit3/
  - assets/images/class8/unit4/
  - assets/images/class8/unit5/
  - assets/images/class8/unit6/
  - assets/images/class8/unit7/
  - assets/images/class8/unit8/

  - assets/images/class9/unit1/
  - assets/images/class9/unit2/
  - assets/images/class9/unit3/
  - assets/images/class9/unit4/
  - assets/images/class9/unit5/
  - assets/images/class9/unit6/
  - assets/images/class9/unit7/
  - assets/images/class9/unit8/
  
  - assets/images/class10/unit1/
  - assets/images/class10/unit2/
  - assets/images/class10/unit3/
  - assets/images/class10/unit4/
  - assets/images/class10/unit5/
  - assets/images/class10/unit6/
  - assets/images/class10/unit7/
  - assets/images/class10/unit8/

  - assets/vocabulary/agriculture.json
  - assets/vocabulary/arts.json
  - assets/vocabulary/business.json
  - assets/vocabulary/climate.json
  - assets/vocabulary/digital.json
  - assets/vocabulary/economics.json
  - assets/vocabulary/education.json
  - assets/vocabulary/entertainment.json
  - assets/vocabulary/family.json
  - assets/vocabulary/food.json
  - assets/vocabulary/government.json
  - assets/vocabulary/health.json
  - assets/vocabulary/history.json
  - assets/vocabulary/home.json
  - assets/vocabulary/nature.json
  - assets/vocabulary/philosophy.json
  - assets/vocabulary/science.json
  - assets/vocabulary/shopping.json
  - assets/vocabulary/space.json
  - assets/vocabulary/sports.json
  - assets/vocabulary/technology.json
  - assets/vocabulary/psychology.json
  - assets/vocabulary/transportation.json
  - assets/vocabulary/travel.json


  - assets/data/practice/reading_comprehension.json